apiVersion: apps/v1
kind: Deployment
metadata:
  name: Pay
  labels:
    app: Pay
spec:
  replicas: 3
  selector:
    matchLabels:
      app: Pay
  template:
    metadata:
      labels:
        app: Pay
    spec:
      containers:
        - name: Pay
          image: username/Pay:latest
          args:
            - /bin/sh
            - -c
            - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
